
import type { Category } from '@/types/pexels';

export const popularSearchQueries: string[] = [
  'Wallpaper',
  'Nature',
  'Technology',
  'Abstract',
  'Minimalist',
  'Space',
  'Animals',
  'City',
  'Food',
  'Travel',
  'Dark',
  'Pattern',
  'Office',
  'Sky',
  'Vintage',
  'Gradient',
  'Texture',
  'Mountains',
  'Forest',
  'Ocean',
  'Flowers',
  'Art',
  'Illustration',
  'Cute',
  'Gaming',
  'Car',
  'Sports',
  'Music',
  'Holiday',
  'Seasonal',
];

export const deviceCategories: Category[] = ['smartphone', 'desktop'];

export const wallpaperCategories: { label: string; value: string }[] = [
  { label: 'Nature', value: 'Nature' },
  { label: 'Technology', value: 'Technology' },
  { label: 'Abstract', value: 'Abstract' },
  { label: 'Minimalist', value: 'Minimalist' },
  { label: 'Space', value: 'Space' },
  { label: 'Animals', value: 'Animals' },
  { label: 'Cityscapes', value: 'City' },
  { label: 'Food & Drink', value: 'Food' },
  { label: 'Travel', value: 'Travel' },
  { label: 'Dark Mode', value: 'Dark' },
  { label: 'Patterns', value: 'Pattern' },
  { label: 'Vintage', value: 'Vintage' },
  { label: 'Gradients', value: 'Gradient' },
  { label: 'Textures', value: 'Texture' },
  { label: 'Mountains', value: 'Mountains' },
  { label: 'Forests', value: 'Forest' },
  { label: 'Oceans', value: 'Ocean' },
  { label: 'Flowers', value: 'Flowers' },
  { label: 'Artistic', value: 'Art' },
  { label: 'Illustrations', value: 'Illustration' },
  { label: 'Cute & Fun', value: 'Cute' },
  { label: 'Gaming', value: 'Gaming' },
  { label: 'Cars', value: 'Car' },
  { label: 'Sports', value: 'Sports' },
  { label: 'Music', value: 'Music' },
  { label: 'Holidays', value: 'Holiday' },
  { label: 'Seasonal', value: 'Seasonal' },
];

export type { Category };
